### ISSUE TITLE
Potential typo

### ISSUE THREAD

**Issue by bplaxco** [connascence/connascence.github.io#3]
Hello,

I could be mistaken, but on the main page I see the word "connascant" used in a few locations, and I think it is spelled [connascent](http://tellspell.com/english/rou/expos/connascent/266143/). If that's not the case feel free to go ahead and close out this issue. ^_^

**Comment by thomir** [comment]
Hi,

Thanks for the bug report - you're absolutely correct. This is now fixed & live on connascence.io.

Cheers,
