### ISSUE TITLE
Serve content over SSL

### ISSUE THREAD

**Issue by tonywok** [connascence/connascence.github.io#4]
Hey there,

Thanks for your work in gathering all this information together!

The content on the site is great, and I often want to share it with people, but I'm hesitant because it's unsecured.

Let me know if there's anything I can do to help!

**Comment by thomir** [comment]
Hi Tony,


Thanks for the bug. I'm working on this right now - should be fixed in a day or two.

Thanks

**Comment by thomir** [comment]
Should be all done now - thanks again for the feedback!

**Comment by tonywok** [comment]
You are awesome! Thank you!
